AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  EnvType: { Type: String, AllowedValues: [prd, dev] }
  LambdaFunctionRole: { Type: String }
  AppTableName: { Type: String }
  WorkerQueue: { Type: String }
  IncidentTopicArn: { Type: String }

Conditions:
  IsProd: !Equals [prd, !Ref EnvType]

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub vrcu-${EnvType}-lambda-FriendListMonitor_Dispatcher
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Timeout: 120
      CodeUri: src
      Role: !Ref LambdaFunctionRole
      Environment:
        Variables:
          APP_GET_TABLE_NAME: !Ref AppTableName
          APP_PUT_TABLE_NAME: !Ref AppTableName
          WORKER_PUT_QUEUE: !Ref WorkerQueue
          DISPATCH_COOLDOWN_SEC: 60
          DISPATCH_COUNT_LIMIT: 100
      Tags:
        EnvType: !Ref EnvType
        Service: VRChatUtility

  LambdaPolicy:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventRuleSchedule.Arn

  EventRuleSchedule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub vrcu-${EnvType}-FriendListMonitor-eventrule
      State: !If [IsProd, ENABLED, DISABLED]
      ScheduleExpression: cron(0 9,21 ? * * *)
      Targets:
        - Id: InvokeFriendListMonitor
          Arn: !GetAtt LambdaFunction.Arn

  CloudWatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub vrcu-${EnvType}-FriendListMonitor_Dispatcher-alarm-err
      AlarmActions:
        - !Ref IncidentTopicArn
      Namespace: AWS/Lambda
      MetricName: Errors
      Unit: Count
      Dimensions:
        - { Name: FunctionName, Value: !Ref LambdaFunction }
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
