AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  EnvType: { Type: String, AllowedValues: [prd, dev] }
  LambdaFunctionRole: { Type: String }
  AppTableName: { Type: String }
  ProcesserQueueArn: { Type: String }
  IncidentTopicArn: { Type: String }

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub vrcu-${EnvType}-lambda-FriendListProcesser
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Timeout: 120
      CodeUri: src
      Role: !Ref LambdaFunctionRole
      Environment:
        Variables:
          APP_GET_TABLE_NAME: !Ref AppTableName
          APP_PUT_TABLE_NAME: !Ref AppTableName
      Tags:
        EnvType: !Ref EnvType
        Service: VRChatUtility

  LambdaPolicy:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: sqs.amazonaws.com
      SourceArn: !Ref ProcesserQueueArn

  LambdaTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      Enabled: True
      FunctionName: !Ref LambdaFunction
      EventSourceArn: !Ref ProcesserQueueArn

  CloudWatchAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub vrcu-${EnvType}-FriendListProcesser-alarm-err
      AlarmActions:
        - !Ref IncidentTopicArn
      Namespace: AWS/Lambda
      MetricName: Errors
      Unit: Count
      Dimensions:
        - { Name: FunctionName, Value: !Ref LambdaFunction }
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
